
package GUI;

import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

    
    public class Customer extends javax.swing.JFrame {
   koneksi koneksi = new koneksi();
    
    private DefaultTableModel model;
    
    private void autonumber(){
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM customer ORDER BY ID_Customer DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String IdCustomer = r.getString("ID_Customer").substring(2);
                String C = "" +(Integer.parseInt(IdCustomer)+1);
                String Nol = "";
                
                if (C.length()==1)
                {Nol = "00";}
                else if (C.length()== 2)
                {Nol = "0";}
                else if(C.length()== 3)
                {Nol = "";}
                
                txtidpembeli.setText("C" + Nol + C);
            }else{
                txtidpembeli.setText("C001");
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println("autonumber error");
        }
    }
        
    public void clear(){
        txtnama.setText("");
        txtalamat.setText("");
        txttelepon.setText("");
        
    }
    public void loadData(){
        model.getDataVector().removeAllElements();
        
        model.fireTableDataChanged();
        
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM customer";
            ResultSet r = s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o = new Object[7];
                o [0] = r.getString("ID_Customer");
                o [1] = r.getString("Nama");
                o [2] = r.getString("Alamat");
                o [3] = r.getString("Telepon");
                
                
                model.addRow(o);
            }
            r.close();
            s.close();
            
        } catch (Exception e) {
            System.out.println("terjadi kesalahan");
        }
    }
    
    public Customer() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        model = new DefaultTableModel();
        
        jtabel.setModel(model);
        
        model.addColumn("ID_Customer");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        
        
        loadData();
        autonumber();
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);

        
    }
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpembeli = new javax.swing.JLabel();
        txtidpembeli = new javax.swing.JTextField();
        lblnama = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        lblalamat = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        lbltelepon = new javax.swing.JLabel();
        txttelepon = new javax.swing.JTextField();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();
        btnkeluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpembeli.setBackground(new java.awt.Color(0, 0, 0));
        lblpembeli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblpembeli.setText("ID Customer");
        getContentPane().add(lblpembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 96, -1, 31));

        txtidpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpembeliActionPerformed(evt);
            }
        });
        getContentPane().add(txtidpembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 96, 144, 31));

        lblnama.setBackground(new java.awt.Color(0, 0, 0));
        lblnama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblnama.setText("NAMA");
        getContentPane().add(lblnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 156, -1, 25));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 152, 144, 33));

        lblalamat.setBackground(new java.awt.Color(0, 0, 0));
        lblalamat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblalamat.setText("ALAMAT");
        getContentPane().add(lblalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, -1, 32));

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 203, 144, 32));

        lbltelepon.setBackground(new java.awt.Color(0, 0, 0));
        lbltelepon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltelepon.setText("TELEPON");
        getContentPane().add(lbltelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 258, -1, 23));
        getContentPane().add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 253, 144, 33));

        btnedit.setBackground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Update");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 80, -1));

        btnsimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        btnhapus.setBackground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        jtabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID PEMBELI", "Nama", "Alamat", "Telepon"
            }
        ));
        jtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 434, 92));

        btnkeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA CUSTOMER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String id = txtidpembeli.getText();
        String nama = txtnama.getText();
        String alamat = txtalamat.getText();
        String telepon = txttelepon.getText();
        
        try {
            Connection c = koneksi.getKoneksi();
            String sql = "INSERT INTO customer VALUES (?,?,?,?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.setString(2, nama);
            p.setString(3, alamat);
            p.setString(4, telepon);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            loadData();
            
        } catch (Exception e){
            System.out.println("Terjadi kesalahan");
            
        } finally {
            autonumber ();
            clear();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        int i = jtabel.getSelectedRow();
        if (i == -1) {
            return;
        }
        String id = (String) model.getValueAt(i, 0);
        String nama = txtnama.getText();
        String alamat = txtalamat.getText();
        String telepon = txttelepon.getText();

        
        try {
            Connection c = koneksi.getKoneksi();
            String sql = "UPDATE customer SET Nama = ?, Alamat = ?, Telepon = ? WHERE ID_Customer = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama);
            p.setString(2, alamat);
            p.setString(3, telepon);
            p.setString(4, id);
            
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data diubah");
            btnsimpan.setEnabled(true);
            btnedit.setEnabled(false);
            btnhapus.setEnabled(false);
            
            
            clear();
        } catch (Exception e) {
            System.out.println("Update error");
        } finally {
            loadData();
            autonumber();
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
         int i = jtabel.getSelectedRow();
        if (i == -1) {
            return;
        }
        
        String id = (String) model.getValueAt(i, 0);
        
        int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin ingin dihapus","konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(pernyataan== JOptionPane.OK_OPTION) {
            try {
                Connection c = koneksi.getKoneksi();
                String sql = "DELETE FROM customer where ID_Customer = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Data terhapus");
            } catch (Exception e) {
                System.out.println("Terjadi Kesalahan");
            } finally{
                btnsimpan.setEnabled(true);
                btnedit.setEnabled(false);
                btnhapus.setEnabled(false);
                loadData();
                autonumber();
                clear();
            }
        }
         if (pernyataan == JOptionPane.CANCEL_OPTION) {
             
         }                                       
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelMouseClicked
         btnsimpan.setEnabled(false);
        btnedit.setEnabled(true);
        btnhapus.setEnabled(true);
        
        int i = jtabel.getSelectedRow();
        if (i == -1) {
            return;
        }
        
        String id = (String) model.getValueAt(i, 0);
        String nama = (String) model.getValueAt(i, 1);
        String alamat = (String) model.getValueAt(i, 2);
        String telepon = (String) model.getValueAt(i, 3);

        txtidpembeli.setText(id);
        txtnama.setText(nama);
        txtalamat.setText(alamat);
        txttelepon.setText(telepon);
        
    }//GEN-LAST:event_jtabelMouseClicked

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        new MenuUtama ().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtidpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtabel;
    private javax.swing.JLabel lblalamat;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblpembeli;
    private javax.swing.JLabel lbltelepon;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtidpembeli;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
